### ISSUE TITLE
Any plans for Android 9?

### ISSUE THREAD

**Issue by Shentao83** [MediatekAndroidDevelopers/android_kernel_vernee_apollo_lite#1]

**Comment by dragonpt** [comment]
We'll go straight to Android Q

**Comment by Shentao83** [comment]
Hey there, any news yet? Can I help betatesting or something?

**Comment by Verevka** [comment]
> Hey there, any news yet? Can I help betatesting or something?

There is no phone for a long time, as there are no plans for it.

**Comment by Shentao83** [comment]
Oh, this is unfortunate. Time to move on to a new phone, then! Next one will be Android One or something, hehe. 

Thanks for everything you have done so far!
